services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: toeic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  libretranslate:
    image: libretranslate/libretranslate:latest
    environment:
      LT_LOAD_ONLY: en,vi
    ports:
      - "5000:5000"
volumes:
  pgdata:
