services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: toeic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  libretranslate:
    # nâng cấp: tra tag mới nhất tại https://hub.docker.com/r/libretranslate/libretranslate/tags rồi sửa version ở đây
    image: libretranslate/libretranslate:v1.9.6
    environment:
      LT_LOAD_ONLY: en,vi
    ports:
      - "5000:5000"
volumes:
  pgdata:
